/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersIndexRouteImport } from './routes/api/users/index'
import { Route as ApiSwaggerIndexRouteImport } from './routes/api/swagger/index'
import { Route as ApiStartupsIndexRouteImport } from './routes/api/startups/index'
import { Route as ApiPlansIndexRouteImport } from './routes/api/plans/index'
import { Route as ApiFavoritesIndexRouteImport } from './routes/api/favorites/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiUsersPlanRouteImport } from './routes/api/users/plan'
import { Route as ApiStartupsIdRouteImport } from './routes/api/startups/$id'
import { Route as ApiPlansSubscribeRouteImport } from './routes/api/plans/subscribe'
import { Route as ApiPlansIdRouteImport } from './routes/api/plans/$id'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth.verify'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIndexRoute = ApiUsersIndexRouteImport.update({
  id: '/api/users/',
  path: '/api/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwaggerIndexRoute = ApiSwaggerIndexRouteImport.update({
  id: '/api/swagger/',
  path: '/api/swagger/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartupsIndexRoute = ApiStartupsIndexRouteImport.update({
  id: '/api/startups/',
  path: '/api/startups/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIndexRoute = ApiPlansIndexRouteImport.update({
  id: '/api/plans/',
  path: '/api/plans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFavoritesIndexRoute = ApiFavoritesIndexRouteImport.update({
  id: '/api/favorites/',
  path: '/api/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersPlanRoute = ApiUsersPlanRouteImport.update({
  id: '/api/users/plan',
  path: '/api/users/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStartupsIdRoute = ApiStartupsIdRouteImport.update({
  id: '/api/startups/$id',
  path: '/api/startups/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansSubscribeRoute = ApiPlansSubscribeRouteImport.update({
  id: '/api/plans/subscribe',
  path: '/api/plans/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansIdRoute = ApiPlansIdRouteImport.update({
  id: '/api/plans/$id',
  path: '/api/plans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/plans/$id': typeof ApiPlansIdRoute
  '/api/plans/subscribe': typeof ApiPlansSubscribeRoute
  '/api/startups/$id': typeof ApiStartupsIdRoute
  '/api/users/plan': typeof ApiUsersPlanRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/favorites': typeof ApiFavoritesIndexRoute
  '/api/plans': typeof ApiPlansIndexRoute
  '/api/startups': typeof ApiStartupsIndexRoute
  '/api/swagger': typeof ApiSwaggerIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/plans/$id': typeof ApiPlansIdRoute
  '/api/plans/subscribe': typeof ApiPlansSubscribeRoute
  '/api/startups/$id': typeof ApiStartupsIdRoute
  '/api/users/plan': typeof ApiUsersPlanRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/favorites': typeof ApiFavoritesIndexRoute
  '/api/plans': typeof ApiPlansIndexRoute
  '/api/startups': typeof ApiStartupsIndexRoute
  '/api/swagger': typeof ApiSwaggerIndexRoute
  '/api/users': typeof ApiUsersIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/plans/$id': typeof ApiPlansIdRoute
  '/api/plans/subscribe': typeof ApiPlansSubscribeRoute
  '/api/startups/$id': typeof ApiStartupsIdRoute
  '/api/users/plan': typeof ApiUsersPlanRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/favorites/': typeof ApiFavoritesIndexRoute
  '/api/plans/': typeof ApiPlansIndexRoute
  '/api/startups/': typeof ApiStartupsIndexRoute
  '/api/swagger/': typeof ApiSwaggerIndexRoute
  '/api/users/': typeof ApiUsersIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/verify'
    | '/api/plans/$id'
    | '/api/plans/subscribe'
    | '/api/startups/$id'
    | '/api/users/plan'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/favorites'
    | '/api/plans'
    | '/api/startups'
    | '/api/swagger'
    | '/api/users'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/verify'
    | '/api/plans/$id'
    | '/api/plans/subscribe'
    | '/api/startups/$id'
    | '/api/users/plan'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/favorites'
    | '/api/plans'
    | '/api/startups'
    | '/api/swagger'
    | '/api/users'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/auth/verify'
    | '/api/plans/$id'
    | '/api/plans/subscribe'
    | '/api/startups/$id'
    | '/api/users/plan'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/favorites/'
    | '/api/plans/'
    | '/api/startups/'
    | '/api/swagger/'
    | '/api/users/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiPlansIdRoute: typeof ApiPlansIdRoute
  ApiPlansSubscribeRoute: typeof ApiPlansSubscribeRoute
  ApiStartupsIdRoute: typeof ApiStartupsIdRoute
  ApiUsersPlanRoute: typeof ApiUsersPlanRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiFavoritesIndexRoute: typeof ApiFavoritesIndexRoute
  ApiPlansIndexRoute: typeof ApiPlansIndexRoute
  ApiStartupsIndexRoute: typeof ApiStartupsIndexRoute
  ApiSwaggerIndexRoute: typeof ApiSwaggerIndexRoute
  ApiUsersIndexRoute: typeof ApiUsersIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/': {
      id: '/api/users/'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swagger/': {
      id: '/api/swagger/'
      path: '/api/swagger'
      fullPath: '/api/swagger'
      preLoaderRoute: typeof ApiSwaggerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/startups/': {
      id: '/api/startups/'
      path: '/api/startups'
      fullPath: '/api/startups'
      preLoaderRoute: typeof ApiStartupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/': {
      id: '/api/plans/'
      path: '/api/plans'
      fullPath: '/api/plans'
      preLoaderRoute: typeof ApiPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favorites/': {
      id: '/api/favorites/'
      path: '/api/favorites'
      fullPath: '/api/favorites'
      preLoaderRoute: typeof ApiFavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/plan': {
      id: '/api/users/plan'
      path: '/api/users/plan'
      fullPath: '/api/users/plan'
      preLoaderRoute: typeof ApiUsersPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/startups/$id': {
      id: '/api/startups/$id'
      path: '/api/startups/$id'
      fullPath: '/api/startups/$id'
      preLoaderRoute: typeof ApiStartupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/subscribe': {
      id: '/api/plans/subscribe'
      path: '/api/plans/subscribe'
      fullPath: '/api/plans/subscribe'
      preLoaderRoute: typeof ApiPlansSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/$id': {
      id: '/api/plans/$id'
      path: '/api/plans/$id'
      fullPath: '/api/plans/$id'
      preLoaderRoute: typeof ApiPlansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiPlansIdRoute: ApiPlansIdRoute,
  ApiPlansSubscribeRoute: ApiPlansSubscribeRoute,
  ApiStartupsIdRoute: ApiStartupsIdRoute,
  ApiUsersPlanRoute: ApiUsersPlanRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiFavoritesIndexRoute: ApiFavoritesIndexRoute,
  ApiPlansIndexRoute: ApiPlansIndexRoute,
  ApiStartupsIndexRoute: ApiStartupsIndexRoute,
  ApiSwaggerIndexRoute: ApiSwaggerIndexRoute,
  ApiUsersIndexRoute: ApiUsersIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
